server:
  applicationConnectors:
  - type: http
    port: 2740
  adminConnectors:
  - type: http
    port: 2741

database:
  driverClass: org.hsqldb.jdbc.JDBCDriver
  url: jdbc:hsqldb:mem:epiphany
  user: sa
  password: sa
  validationQuery: SELECT * FROM INFORMATION_SCHEMA.SYSTEM_TABLES